name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    paths: 
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Upload Episode from YouTube To Anchor.Fm
        working-directory: ./
        run: ls .
        shell: bash
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
